# common keys
JK_PROTO = "PROTO"
JK_HEADER = "HEADER"
JK_PAYLOAD = "PAYLOAD"
JK_EMSG = "EMSG"

# keys for field/attribute name
JK_EN10MB = "EN10MB"
JK_EN10MB_DMAC = JK_EN10MB + ".DMAC"
JK_EN10MB_SMAC = JK_EN10MB + ".SMAC"
JK_EN10MB_TYPE = JK_EN10MB + ".TYPE"

JK_DLT_NULL = "DLT_NULL"
JK_DLT_NULL_AF = JK_DLT_NULL + ".AF"

